name: compose-post-service
schedulerName: epl-scheduler
ports:
  - port: 9090
    targetPort: 9090

container:
  command: ComposePostService
  image: deathstarbench/social-network-microservices
  name: compose-post-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

annotations:
  dependedby.text-service.bw: "800000"
  dependedby.text-service.latency: "1"
  dependedby.media-service.bw: "800000"
  dependedby.media-service.latency: "10"
  dependedby.unique-id-service.bw: "40000"
  dependedby.unique-id-service.latency: "1"
  dependedby.url-shorten-service.bw: "80000"
  dependedby.url-shorten-service.latency: "1"
  dependson.post-storage-service.bw: "40000"
  dependson.post-storage-service.latency: "10"
  dependson.home-timeline-service.bw: "40000"
  dependedby.nginx-thrift.bw: "40000"
  dependson.user-timeline-service.bw: "40000"
