name: post-storage-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: PostStorageService
  image: deathstarbench/social-network-microservices
  name: post-storage-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

annotations:
  dependson.post-storage-memcached.bw: "80000000"
  dependson.post-storage-memcached.latency: "1"
  dependson.post-storage-mongodb.bw: "800000"
  dependson.post-storage-mongodb.latency: "1"
  dependedby.user-timeline-service.bw: "8000000"
  dependedby.user-timeline-service.latency: "1"
  dependson.user-service.bw: "800000"
  dependson.user-service.latency: "1"
  dependedby.compose-post-service.bw: "40000"
  dependedby.compose-post-service.latency: "1"
  dependedby.home-timeline-service.bw: "28000000"
