name: text-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: TextService
  image: deathstarbench/social-network-microservices
  name: text-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

annotations:
  dependson.user-service.bw: "80000"
  dependson.user-service.latency: "1"
  dependson.compose-post-service.bw: "800000"
  dependson.compose-post-service.latency: "1"
  dependedby.nginx-thrift.bw: "8000000"
  dependedby.nginx-thrift.latency: "10"
