name: user-timeline-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: UserTimelineService
  image: deathstarbench/social-network-microservices
  name: user-timeline-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

annotations:
  dependson.user-timeline-mongodb.bw: "8000000"
  dependson.user-timeline-mongodb.latency: "10"
  dependson.user-timeline-redis.bw: "8000000"
  dependson.user-timeline-redis.latency: "1"
  dependedby.home-timeline-service.latency: "5"
  dependedby.home-timeline-service.bw: "80000"
  dependson.post-storage-service.bw: "8000000"
  dependson.post-storage-service.latency: "1"
  dependson.user-service.bw: "800000"
  dependson.user-service.latency: "1"
  dependedby.compose-post-service.bw: "40000"
  dependedby.nginx-thrift.bw: "8000000"
