name: user-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: UserService
  image: deathstarbench/social-network-microservices
  name: user-service
  ports: 
  - containerPort: 9090

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

annotations:
  dependedby.social-graph-service.bw: "800000"
  dependedby.social-graph-service.latency: "10"
  dependson.user-mongodb.bw: "800000"
  dependson.user-mongodb.latency: "10"
  dependson.user-memcached.bw: "80000"
  dependson.user-memcached.latency: "1"
  dependedby.user-timeline-service.bw: "800000"
  dependedby.user-timeline-service.latency: "1"
  dependedby.post-storage-service.bw: "800000"
  dependedby.post-storage-service.latency: "1"
  dependedby.text-service.bw: "80000"
  dependedby.text-service.latency: "1"
